### ISSUE TITLE
Add support for new nvim-treesitter highlight groups

### ISSUE THREAD

**Issue by Lilja** [EdenEast/nightfox.nvim#217]
## Description
As stated [here](https://github.com/nvim-treesitter/nvim-treesitter/pull/3656#issuecomment-1279998539), the old `TS*` highlight groups are deprecated. They should now be migrated.

Some links:
[commit + github discussion](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f)
[reddit](https://www.reddit.com/r/neovim/comments/y5rofg/recent_treesitter_update_borked_highlighting/)
folke, author of [tokyonight](https://github.com/folke/tokyonight.nvim) has a way [to migrate](https://www.reddit.com/r/neovim/comments/y5rofg/recent_treesitter_update_borked_highlighting/isn45gl/).

**Comment by EdenEast** [comment]
This issue has been resolved with commit [6585499](https://github.com/EdenEast/nightfox.nvim/commit/65854998c139822ef0a8874364840b3fe80ea624).

**Comment by colepeters** [comment]
@EdenEast Unfortunately I'm still seeing highlighting as broken over here: 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1713932/196826073-e2e56f74-c3b2-4673-87ad-ff520b91a3fd.png">

I'm on Neovim 0.8.0 with the latest Treesitter as well. Not sure if I'm perhaps missing something else, but I have found [adding this to my config](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#commitcomment-87014462) seems to restore highlighting as expected, if that helps?

**Comment by EdenEast** [comment]
If you have a compile file make sure that you either clean it or regenerate it. From what I can see they are still linking to syntax highlight groups. (ex. `@comment` links to `Comment` so that does not have to be set).

**Comment by colepeters** [comment]
@EdenEast Yup, I regenerated my compile file before, and just now manually deleted it before regenerating it again. Unfortunately I'm still missing a bunch of highlights as seen above. Could you tell me how I can figure out which highlights are missing in a way that works for you? I'm unfamiliar with how to do this. Thanks!

**Comment by EdenEast** [comment]
You could try this. Create a new `scratch.lua` file and paste this example config. Execute `NightfoxInteractive` in this file and nightfox will do a clean reload of its configuration every time you save. Playing with commenting out different sections should help narrow down what ones it is.

<details>
<summary>scratch.lua</summary>

```lua
require("nightfox").setup({
  groups = {
    all = {
      -- ["@comment"] = { link = "Comment" },
      -- ["@none"] = { bg = "NONE", fg = "NONE" },
      -- ["@preproc"] = { link = "PreProc" },
      -- ["@define"] = { link = "Define" },
      -- ["@operator"] = { link = "Operator" },

      -- ["@punctuation.delimiter"] = { link = "Delimiter" },
      -- ["@punctuation.bracket"] = { link = "Delimiter" },
      -- ["@punctuation.special"] = { link = "Delimiter" },

      -- ["@string"] = { link = "String" },
      -- ["@string.regex"] = { link = "String" },
      -- ["@string.escape"] = { link = "SpecialChar" },
      -- ["@string.special"] = { link = "SpecialChar" },

      -- ["@character"] = { link = "Character" },
      -- ["@character.special"] = { link = "SpecialChar" },

      -- ["@boolean"] = { link = "Boolean" },
      -- ["@number"] = { link = "Number" },
      -- ["@float"] = { link = "Float" },

      -- ["@function"] = { link = "Function" },
      -- ["@function.call"] = { link = "Function" },
      -- ["@function.builtin"] = { link = "Special" },
      -- ["@function.macro"] = { link = "Macro" },

      -- ["@method"] = { link = "Function" },
      -- ["@method.call"] = { link = "Function" },

      -- ["@constructor"] = { link = "Special" },
      -- ["@parameter"] = { link = "Identifier" },

      -- ["@keyword"] = { link = "Keyword" },
      -- ["@keyword.function"] = { link = "Keyword" },
      -- ["@keyword.operator"] = { link = "Keyword" },
      -- ["@keyword.return"] = { link = "Keyword" },

      -- ["@conditional"] = { link = "Conditional" },
      -- ["@repeat"] = { link = "Repeat" },
      -- ["@debug"] = { link = "Debug" },
      -- ["@label"] = { link = "Label" },
      -- ["@include"] = { link = "Include" },
      -- ["@exception"] = { link = "Exception" },

      -- ["@type"] = { link = "Type" },
      -- ["@type.builtin"] = { link = "Type" },
      -- ["@type.qualifier"] = { link = "Type" },
      -- ["@type.definition"] = { link = "Typedef" },

      -- ["@storageclass"] = { link = "StorageClass" },
      -- ["@attribute"] = { link = "PreProc" },
      -- ["@field"] = { link = "Identifier" },
      -- ["@property"] = { link = "Identifier" },

      -- ["@variable"] = { link = "Normal" },
      -- ["@variable.builtin"] = { link = "Special" },

      -- ["@constant"] = { link = "Constant" },
      -- ["@constant.builtin"] = { link = "Special" },
      -- ["@constant.macro"] = { link = "Define" },

      -- ["@namespace"] = { link = "Include" },
      -- ["@symbol"] = { link = "Identifier" },

      -- ["@text"] = { link = "Normal" },
      -- ["@text.title"] = { link = "Title" },
      -- ["@text.literal"] = { link = "String" },
      -- ["@text.uri"] = { link = "Underlined" },
      -- ["@text.math"] = { link = "Special" },
      -- ["@text.environment"] = { link = "Macro" },
      -- ["@text.environment.name"] = { link = "Type" },
      -- ["@text.reference"] = { link = "Constant" },

      -- ["@text.todo"] = { link = "Todo" },
      -- ["@text.note"] = { link = "SpecialComment" },
      -- ["@text.warning"] = { link = "WarningMsg" },
      -- ["@text.danger"] = { link = "ErrorMsg" },

      -- ["@tag"] = { link = "Tag" },
      -- ["@tag.attribute"] = { link = "Identifier" },
      -- ["@tag.delimiter"] = { link = "Delimiter" },
    },
  },
})
```

</details>

**Comment by colepeters** [comment]
Thank you!

It looks like uncommenting the following two gets me a lot closer:

```lua
      ["@tag"] = { link = "Tag" },
      ["@tag.attribute"] = { link = "Identifier" },
```

The results:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/1713932/196835288-a373a428-7479-4bc0-a46e-73c1bbd0d2a1.png">

However, there are still two lingering differences which I wasn't able to resolve:

1. HTML tag names used to be purple, with their brackets dark blue; currently, the tag names and the brackets are both dark blue
2. Attribute names used to be dark blue; above, they are cyan

Here's a comparison for reference:

<table>
<thead>
  <tr>
    <th>Before</th>
    <td>Current</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>
      <img width="250" alt="image" src="https://user-images.githubusercontent.com/1713932/196836257-74488b58-6d01-45d2-946c-dc4d13294d3c.png" />
    </td>
    <td>
      <img width="250" alt="image" src="https://user-images.githubusercontent.com/1713932/196835672-69bf81d9-a4f8-4023-a62e-3d7298fddf72.png" />
    </td>
  </tr>
</tbody>
</table>

**Comment by colepeters** [comment]
Playing with this a little more, I managed to get things back to how they were before using these values:

```lua
      ["@tag"] = { link = "Keyword" },
      ["@tag.attribute"] = { link = "Function" },
      ["@tag.delimiter"] = { link = "Delimiter" },
```
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1713932/196837560-fb269894-e111-456a-84b9-19221e2c57c6.png">

Maybe some colour specifications were shifted in this update…?

**Comment by vycoder** [comment]
> Playing with this a little more, I managed to get things back to how they were before by using these values:
> 
> ```lua
>       ["@tag"] = { link = "Keyword" },
>       ["@tag.attribute"] = { link = "Function" },
>       ["@tag.delimiter"] = { link = "Delimiter" },
> ```
> 
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/1713932/196837560-fb269894-e111-456a-84b9-19221e2c57c6.png">
> 
> Maybe some colour specifications were shifted in this update…?

seconding this. I encountered the same issue. this fixed my troubles as well.

**Comment by EdenEast** [comment]
Added the missing links in a new pr. Let me know if there are any other highlight groups that have changed. Will pin this issue for a bit for others that might have found another.

**Comment by colepeters** [comment]
Looks like `@text` has changed as well. I fixed mine with:
```lua
["@text"] = { link = "Normal" },
```

**Comment by EdenEast** [comment]
Looking at the commit that removed the obsolete TS* highlight groups it looks like that [text](https://github.com/nvim-treesitter/nvim-treesitter/pull/3656/files#diff-abe9340bd01507758ed66cde7e84ccf0e982393366df6524b73e48a7c758ca9cL249) is linked to `TSNone`.

**Comment by EdenEast** [comment]
Looking at what it should be I agree that it should have the default foreground. I have an open pr that I will be adding to if there are new issues found.

**Comment by colepeters** [comment]
Thanks @EdenEast, everything's looking back to normal now! Much appreciated.
